FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json .
RUN npm install --legacy-peer-deps
COPY frontend/ .
# Vite config sẽ được override bởi env VITE_API_URL
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
